### ISSUE TITLE
[BUG]年历通书进度无法获得

### ISSUE THREAD

**Issue by sjdhome** [dong031001/EnigTech2#111]
**描述BUG**
在1.2.0版本中年历通书成就无法获得。
**如何重现**
在1.2.0版本中新建或打开已有存档，尝试获取年历通书
**原本期望**
若无此BUG，原本你期待发生什么？
获得年历通书后能解锁相应进度
**截图**
![image](https://user-images.githubusercontent.com/11871061/70432491-5d503c00-1aba-11ea-828c-032f27463e72.png)
![image](https://user-images.githubusercontent.com/11871061/70432503-65a87700-1aba-11ea-8e28-2e3b3f92ee9b.png)

**运行环境（请越详细越好）:**
 - 操作系统*：Windows 10 x64
 - 运行内存：16GB
 - Java版本：Java 8
- 整合包版本*：1.2.0

**错误报告**
若游戏崩溃，请附上游戏根目录下crash-report文件夹内最新的文件

**Comment by dong031001** [comment]
由错误的依赖进度导致，感谢反馈
