### ISSUE TITLE
[BUG]无法使用炼油气制造液态乙烯

### ISSUE THREAD

**Issue by Control-Core** [dong031001/EnigTech2#116]
**描述BUG**
无法将炼油气倒入简易流体蒸馏器中
**如何重现**
使用桶装炼油气右键简易流体整流器
**原本期望**
若无此BUG，原本你期待发生什么？
期望可以将炼油气制作为液态乙烯
**截图**

**运行环境（请越详细越好）:**
 - 操作系统*：
 - 运行内存：
 - Java版本：
- 整合包版本*：

**错误报告**
若游戏崩溃，请附上游戏根目录下crash-report文件夹内最新的文件

**Comment by dong031001** [comment]
尝试过使用高压液体导管导入吗？
