### ISSUE TITLE
[BUG]togetherforever同步暮色进度导致服务器后台刷屏，假死

### ISSUE THREAD

**Issue by Yunth233** [dong031001/EnigTech2#118]
**描述BUG** 和队友一起进时暮色卡住，服务器后台刷屏：击杀娜迦时卡住，后台刷屏，服务器假死，玩家交互无响应，一段时间后断开连接。（怀疑是同步进度导致）

**截图**

![001](https://user-images.githubusercontent.com/58768174/70685229-b8b14280-1ce3-11ea-9e5c-7c77bf00e954.jpg)
![002](https://user-images.githubusercontent.com/58768174/70685240-bf3fba00-1ce3-11ea-8391-baf1993fccb6.jpg)
![003](https://user-images.githubusercontent.com/58768174/70685248-c36bd780-1ce3-11ea-8a3b-819a58fb486c.jpg)

**运行环境:**
 - 操作系统*：win10
 - 运行内存：5.5G
 - Java版本：jdk-8.0.212.04-openj9
- 整合包版本*：1.2.3
插件:
spongeforge-1.12.2-2838-7.1.7
{权限}LuckPerms-Sponge-4.3.75
{全息}holograms-3.1.5
{物品禁用}EpicBanItem-0.3.2-b268
[扫地]soulLaggRemover-1.1

**Comment by dong031001** [comment]
图没截全，前面Exception Trace部分刚好看不见，重现失败，请添加更多信息

**Comment by dong031001** [comment]
这图还是没截全啊...推荐你将crash-report文件夹下对应文件上传，若无崩溃泽上传logs文件夹下对应文件的对应部分或是整体上传

**Comment by Yunth233** [comment]
辛苦您了，服务器暂时没出现问题。φ(>ω<*)

**Comment by Yunth233** [comment]
辛苦您了。φ(&gt;ω<*)&nbsp;


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"dong031001"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月12日(星期四) 晚上8:50
收件人:&nbsp;"dong031001/EnigTech2"<EnigTech2@noreply.github.com&gt;;
抄送:&nbsp;"淰仴顔"<1137895963@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [dong031001/EnigTech2] [BUG]togetherforever同步暮色进度导致服务器后台刷屏，假死 (#118)




这图还是没截全啊...推荐你将crash-report文件夹下对应文件上传，若无崩溃泽上传logs文件夹下对应文件的对应部分或是整体上传
