### ISSUE TITLE
[BUG]以全屏模式打开游戏后新建或开启存档时会卡死

### ISSUE THREAD

**Issue by sjdhome** [dong031001/EnigTech2#122]
**描述BUG**
以全屏模式开启游戏后（提前在游戏内设置好）新建或打开存档会提示 Java 无响应，如果点击“尝试还原此程序”之后会变成空白，按ESC返回主界面之后再次进入就正常了。
***并且1.0.6版内没有此问题***

**如何重现**
以全屏模式开启游戏后（提前在游戏内设置好）新建或打开存档。
**原本期望**
若无此BUG，原本你期待发生什么？
正常进入游戏
**截图**
![无标题](https://user-images.githubusercontent.com/11871061/70788029-f210ad80-1dca-11ea-8e66-089839960e2a.png)

**运行环境（请越详细越好）:**
 - 操作系统*：Windows 10 x64
 - 运行内存：16GB
 - Java版本：Java 8
- 整合包版本*：1.2.0

**错误报告**
若游戏崩溃，请附上游戏根目录下crash-report文件夹内最新的文件
没有crash-report文件夹，但有MultiMC提供的日志。
[日志.txt](https://github.com/dong031001/EnigTech2/files/3959938/default.txt)

**Comment by dong031001** [comment]
无响应后等待片刻即可
