### ISSUE TITLE
鞣制皮革（改良背包）与鞣制皮革（生存主义）的消歧义

### ISSUE THREAD

**Issue by ChromaPIE** [dong031001/EnigTech2#39]
两种同名不同用，配方也不同的二次产品显然会引起疑惑。我在游玩时准备制作改良背包中的背包，粗略查询了JEI，看到需要4份鞣制皮革（改良背包）后，因为先入为主，第一反应是去用生存主义的方法制作 **先前已经制作过的** 鞣制皮革（生存主义）。而后才发现两者完全不是一回事。建议是变更改良背包中“鞣制皮革”的显示名为“强化”“加工”‘硬质’（来源于生存主义中鞣制皮革的矿辞名之一：_materialHardenedLeather_。顺便，潘马斯中已有“硬化皮革”）。

或者，，，综合一下，用ct来实现统一用改良背包里的捆扎皮革放进晾干架来制作通用的鞣制皮革？？

**Comment by dong031001** [comment]
后者会好点
