### ISSUE TITLE
德鲁伊的紫水晶交易问题与工程师的铜锭交易问题

### ISSUE THREAD

**Issue by ChromaPIE** [dong031001/EnigTech2#46]
- 由于紫水晶（寂静宝石）与紫水晶（神秘世界）共有gemAmethyst的矿辞名，故经过铁匠辞典（热力基本）将较为廉价的紫水晶（寂静宝石）转化为不那么容易获得的紫水晶（神秘世界）可以从德鲁伊手中诈骗到少则8个，多则数十个绿宝石。

   建议：为紫水晶（神秘世界）**修改**或新增一条矿辞名，仅为防止铁匠辞典转化。（crystalAmethyst，Amethyst，materialAmethyst）。Anyway，不建议ban掉铁匠辞典。

- 这项问题初次发现于私包存档，经过测试et2中依然存在：在沉浸工程的工程师手中可以用铜锭（沉浸工程）来换取绿宝石，但InstantUnify模组似乎会将玩家物品栏中所有的ingotCopper立即全部转化为铜锭（热力基本），导致交易无法成功。此问题的解决方式想也极多，比如修改InstantUnify配置来提高铜锭（沉浸工程）的优先级，或是直接ban掉交易等等，任君定夺。

**Comment by dong031001** [comment]
修改矿辞+移除交易，下次更新修复
