### ISSUE TITLE
添加一个辅助功能类MOD的建议

### ISSUE THREAD

**Issue by huangsijun17** [dong031001/EnigTech2#56]
建议在ET和ET2添加MOD：
[Findme](https://www.curseforge.com/minecraft/mc-mods/findme)，以便于在前中期快速从箱子中寻找物品。

**Comment by dong031001** [comment]
采纳建议，将会在ET2-0.5.1b更新中附

**Comment by dong031001** [comment]
最好可以直接发PR申请，看起来会方便一点
