### ISSUE TITLE
[崩溃]大佬 在下刚才启动服务器，闪过一段东西之后就控制台自动关闭了，

### ISSUE THREAD

**Issue by snowyue** [dong031001/EnigTech2#87]
**描述BUG**
大佬打扰了，刚才在下启动bat文件后，闪过2段红色 控制台就没有了
**如何重现**

**原本期望**
若无此BUG，原本你期待发生什么？
正常运行
**截图**

**运行环境（请越详细越好）:**
 - 操作系统*：win10-1803 x64
 - 运行内存：24
 - Java版本：java8 u231
- 整合包版本*：1.0.6

**错误报告**
若游戏崩溃，请附上游戏根目录下crash-report文件夹内最新的文件

**Comment by snowyue** [comment]
链接：https://pan.baidu.com/s/1bF9Z3BUA-6wTz2GIRqSleA 
提取码：kvz4 
复制这段内容后打开百度网盘手机App，操作更方便哦

**Comment by dong031001** [comment]
同意Eula.txt下条款后即可正常运行
将false改为true

**Comment by snowyue** [comment]
谢谢大佬，我很久没玩mc都忘了协议了，
好像控制台还是会有输出红色的文本
